### ISSUE TITLE
Bleutrade sets a max nonce

### ISSUE THREAD

**Issue by claytondukes** [cryptoeax/arbbot#107]
I noted in [Bleutrade's API docs](https://bleutrade.com/help/API) that they say:

```
nonce is a number that should never be repeated and always greater than the previous number. Is used to increase your safety, is optional, but if it is first used, it becomes mandatory. Max = 2147483647.
```
But in `bot/Exchange.php`, the nonce is set using `microtime( true )`.

I'm not sure if this is the cause of the Bleutrade issues, but thought it might be worth investigating.

I also notice that other api's/scripts, etc. just use `time()` so it wasn't clear to me why arbbot is using microseconds. 

```
 protected function nonce() {

    static $previousNonce = array( );
    $id = $this->getID();
    if ( !isset( $previousNonce[ $id ] ) ) {
      $previousNonce[ $id ] = 0;
    }

    // Try the current time, if we're getting called too fast, step up one by one.
    $nonce = floor( microtime( true ) * 1000000);
    if ( $nonce <= $previousNonce[ $id ] ) {
      $nonce = $previousNonce[ $id ] + 1;
    }

    $previousNonce[ $id ] = $nonce;
    return $nonce;

  }
```

**Comment by cryptoeax** [comment]
We use microseconds in order to get a higher resolution.  We can probably mask off anything above the higher 32-bits.  But this is a disruptive change, since it will mean all nonce values will suddenly decrease, which effectively means people will need to regenerate their API keys.  So there should be a good reason why we would change our behavior here...

**Comment by cryptoeax** [comment]
I don't think there is anything that we should do here.  Closing the issue.
