### ISSUE TITLE
auto-balance missing in config

### ISSUE THREAD

**Issue by claytondukes** [cryptoeax/arbbot#125]
I was comparing a new install vs my install from a couple of weeks ago and noticed that my `config.ini` was missing:

```
; The autobalance module will automatically balance the wallets across exchanges depending on the current needs and pending deposits.
auto-balance = true
```

**Comment by cryptoeax** [comment]
config.ini isn't tracked in this repository.  Keeping it up to date is up to you.

**Comment by claytondukes** [comment]
Yep, I know. Just wonder if there's a good way to let people know. Maybe just a message during startup or the web ui? (just thought someone else will miss stuff like that also)

**Comment by cryptoeax** [comment]
The config variables usually have good default values, so that's usually not needed.  For example, the default value for this variable is `true`, so if you forget to specify it, the module will default to be enabled, which is what most of the users want.  The reason why I added this config variable was to enable people who want to *disable* the auto-balancing to have a way to do that.  :-)

In the cases where I have made a change to the code which didn't have an obvious upgrade strategy, the bot has prompted the user asking what to do on startup, but this has so far only happened a couple of times in the past.  I'm trying hard to keep the bot as smart and non-nagging as possible.

FWIW, when #91 gets fixed, the config file format will change in a way that would make this all make much more sense.  After that change, instead of having to copy `config.ini.example` into `config.ini`, you basically create empty `ini` files and write the variables you want to override in them and only those variables.  Everything else will use the default values, and `config.ini.example` will be used as a way to see what those defaults are (not to be modified by the user.)  This is effectively how the bot works already, but it's not very clear to the user.  But if you have a variable in your `config.ini` file which is just specifying the default value as you see in `config.ini.example`, specifying that variable in `config.ini` and omitting it result in the same outcome.
