### ISSUE TITLE
arbbot for more exchanges

### ISSUE THREAD

**Issue by MAURORANTE** [cryptoeax/arbbot#131]
Hello, I'm Brazilian, I do not speak English, I translated this text through google translator. 

I would like to use the arbbot with several exchanges, but my knowledge of php is limited. 

I need to implement some more exchanges on the arbbot. The exchanges I need are binance, bitfinex, bitmex, bittrex (it's already), bleutrade (it's already), bresiliex, btcchina, cryptopia, foxbit, hitbtc, mercado_bitcoin, poloniex. I do not know how to do this using ccxt. 

Can you explain to me how to do it or do you do this service and charge for it? 

How much would you charge to hand me the arbbot with all those exchanges working for arbitrage?

Taking advantage of the message, what is the minimum acceptable value for arbbot to work efficiently and generate good results. 

Thanks in advance and I await your return.

My whatsapp is +5511970157855

**Comment by cryptoeax** [comment]
Please see #5 for the continued effort for more exchange support.  This is an open source project and if you would like to help with its development you are welcome to donate to the project using the donation addresses provided in the README file.  :-)  Otherwise please feel free to get in touch using gitter.
