### ISSUE TITLE
Why the bot has not done any Trade?

### ISSUE THREAD

**Issue by andreserna11** [cryptoeax/arbbot#21]
I've been waiting 12 hours for a trade and has not done any.

What should I organize or how long should I wait for firts trade?

**Comment by cryptoeax** [comment]
Have you set any autobuy funds yet, as described in the README?

**Comment by andreserna11** [comment]
Thanks for the above.

I already made my first Trade, now what should I do?

another question, should I activate the settlement module?

**Comment by cryptoeax** [comment]
> Thanks for the above.
> 
> I already made my first Trade, now what should I do?

Nothing!  The bot is designed to run autonomously without human intervention, so you should be able to leave it running and just watch over it.  :-)  As the bot makes more trades, you will hopefully see your total BTC balance grow gradually over time.  (Note that this takes hundreds/thousands of trades since profits are made in satoshis and sometimes a trade results in a loss, but you want your bot to run at a 80%+ profitable trade percentage rate so its profits would grow over time.)

Also note that the bot is under active development, and you want to check regularly for updates to the bot especially given the current turbulent BTC markets (since sometimes I need to make code adjustments to make the bot work well in the current market).  When you get newer versions please check config.ini.example for changes in case new configuration options have been made available to enhance the configurability of the bot.

> another question, should I activate the settlement module?

If you mean the take-profit module, that is up to you.  I suggest leaving it off for a while and let the bot purchase some funds and grow its portfolio and make some trades and watch it for a while so that you get the hang of it.  You will see that the bot will start to watch some altcoins that it determines to be suitable for arbitrage, and it may want to purchase more of some of them.  That means that you may want to allocate more autobuy funds towards making your portfolio bigger.  The reason is that a larger portfolio means the bot can make more trades and have a higher chance at making profits while doing so, so if you extract profits from the BTC balance too soon (or just choose to maintain a really high BTC balance without setting up a good altcoin balance) you will be hurting the maximum profitability of your bot.

Adjusting things to the sweet spot requires some experimentation and I suspect is kind of unique to each bot's processing/network characteristics which would determine the types of arbitrage opportunities it gets to successfully act on.

If there is nothing else to be done here, please feel free to close the issue.  Good luck using the bot!  If you have ideas for improving it please file more issues.

**Comment by andreserna11** [comment]
Thanks bro!

I'll put it to work.
