### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by Penushi** [cryptoeax/arbbot#23]
Hello,
first, thank you for you work @cryptoeax :)

1. How many btc must have both exchanges? is 0,025 btc each exchange enough, for first small start?
2. How dedect the bot wallet adress from exchanges for transfering coins? automatic? I just Need Key+Secret and the bot make the rest?
3. Buy the bot after start on both exchange coins? so After start the bot, the bot buy a profitable coin on both exchanges and then wait for arbitrage to sell and buy and then to Transfer coins? or how works the bot with fresh accounts without any coins?

thank you :)

**Comment by cryptoeax** [comment]
> Hello,
> first, thank you for you work @cryptoeax :)

You're welcome!

>     How many btc must have both exchanges? is 0,025 btc each exchange enough, for first small start?

Yes.  That is probably too small to start with.  I recommend starting with ~0.3-0.5BTC total, but I have to say that I haven't tested a whole lot of different configurations.  In general, the smaller you start with, the longer it will take for your bot to be able to become effective, since you need to have enough balance to purchase some altcoins and also be able to trade large enough amounts to cover the various fees involved.

Note that the last time I checked the BTC transfer fee on bittrex was 0.001 BTC, so that's already 4% of your total seed fund going into one round of rebalancing your BTC wallets...  :-)

(BTW you don't need to worry about splitting your seed BTC fund across exchanges manually, the bot will do it for you.)

>     How dedect the bot wallet adress from exchanges for transfering coins? automatic? I just Need Key+Secret and the bot make the rest?

It is all automatic.  The bot is fully autonomous.  In the future the bot will need you to download two files from your exchange and it will tell you when you start it, but in general the bot is designed to run without human interaction.  Sometimes transfers also get stuck because exchanges aren't 100% ideal organizations ;-) and the bot alerts you about those stuck transfers so that you can open support tickets for them.

My interest here is to have something that can generate a revenue stream without requiring me to do a lot of manual work.  :-)

>     Buy the bot after start on both exchange coins? so After start the bot, the bot buy a profitable coin on both exchanges and then wait for arbitrage to sell and buy and then to Transfer coins? or how works the bot with fresh accounts without any coins?

I don't completely understand your question but I think you're asking how the bot works, which suggests you haven't fully studied the README file, which completely explains this.  :-)  Please follow the steps there to set some autobuy funds to let the buy start when you have a larger BTC balance on your exchanges.

**Comment by Penushi** [comment]
Allright thank you :) 

Last Question: Have the bot a logfile that i can find on the hdd? or only in the webinterface?

**Comment by cryptoeax** [comment]
The log is stored in the mysql database, in the `log` table.  It should be easy to export it to a file if you need to.

I'm going to close the issue now.  :-)
