### ISSUE TITLE
previous version exploit

### ISSUE THREAD

**Issue by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [cryptoeax/arbbot#51]
@ cryptoeax
yep, I was the guy who called out the php backdoor in the other repo, also i doubt that guy was the creator anyway.

I have some additions ive made myself, should you like to chat. let me know if you have a keybase or any chat client. 

EDIT; wasn't it hilarious the other guy had a "PHP Backdoors" repo forked in his profile? I swear people these days.

**Comment by cryptoeax** [comment]
> @ cryptoeax
> yep, I was the guy who called out the php backdoor in the other repo, also i doubt that guy was the creator anyway.

Thanks!  Yes, based on the code I suspect the original codebase was quite old, since it refers to some old exchanges like Cryptsy (https://github.com/cryptoeax/arbbot/blob/4426c1075798a002b7eba81dc1a95a1d1513922f/web/ui.js#L103).  It was also quite buggy in the beginning so my best guess was that this was some code best this person got their hands on somehow...

> I have some additions ive made myself, should you like to chat. let me know if you have a keybase or any chat client.

I've made a gitter room for this project (https://gitter.im/cryptoeax-arbbot/Lobby) where I just sent you an invite.

> EDIT; wasn't it hilarious the other guy had a "PHP Backdoors" repo forked in his profile? I swear people these days. 

Yeah :(  Sadly they successfully managed to steal some BTC from at least one user before github pulled their repo down...

**Comment by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [comment]
yep. some people just lack true talent and mitigate by preying on others. anyway, ill be sure to pop in the gitter sometime today. thanks for invite.

**Comment by cryptoeax** [comment]
Closing this issue as part of regular clearnup!
