### ISSUE TITLE
P&L work not correct

### ISSUE THREAD

**Issue by Scorpic1** [cryptoeax/arbbot#6]
I think P&L worked not correct. P&L without cost on exchange (0,2%) Please included it and check same.

![2017-12-06_001657](https://user-images.githubusercontent.com/18716398/33631348-5be8d85e-da1b-11e7-9af0-bb5ea593583c.jpg)
![2017-12-06_002518](https://user-images.githubusercontent.com/18716398/33631655-3f49f5e2-da1c-11e7-9849-24292a175114.jpg)
Impossible.
![2017-12-06_003520](https://user-images.githubusercontent.com/18716398/33632084-a19d351e-da1d-11e7-8391-eb468adf716f.jpg)

**Comment by cryptoeax** [comment]
I don't follow.  P&L without cost doesn't mean anything.  You can't have a "loss" without taking cost into consideration.  :-)

The number reported here for each trade is the amount sold - amount bought - all trade/transfer fees.  The total sum of all of the total unrealized P&L.  There are other things that could be reported here, and if there is a useful metric to report I'd be happy to add it (but just because another site reports something in a specific way isn't a good reason, an exchange site's UI isn't a good interface for an arbitrage bot.)

To give you a good idea of my thinking behind reporting this number specifically, I have been looking for metrics that allow me to monitor the profitability of the bot, in order to make changes to its code to maximize the amount of profits that it is making.

**Comment by Scorpic1** [comment]
14% in one day is impossible profit, i think without exchange cost.

**Comment by cryptoeax** [comment]
> 14% in one day is impossible profit, i think without exchange cost.

You realize that amount is in BTC not a percentage, right?

**Comment by cryptoeax** [comment]
Also please note that each trade incurs a risk, so as the bot works you may see a trade that has for example 0.04BTC loss, which would drive down the total unrealized P&L quite a lot in one shot!  But 0.014 BTC for 118 trades like sounds quite reasonable performance to me.

**Comment by Scorpic1** [comment]
Need see net profit, because you pay fee to exchange to any buy/sell coins.

**Comment by cryptoeax** [comment]
The fees for the trades are taken into account as I mentioned before.

**Comment by Scorpic1** [comment]
In P&L summ in Amount and Bought without fee exchange if you add fee exchange spead will be in minus and with loss. 
And Profit/Loss - not correct, without fee exchange, need see net profit (loss) with fee exchange. I think and total P&L without exchange fee.
Better add in bot spread in percentages (percentage difference).
For example if percentage difference spread more 1% enter into trade, do not enter into trade less.

**Comment by Scorpic1** [comment]
Example in pictures. Last trade in bot. Coin LBC.
Qty 84.75581611 LBC 
Rate 0.00002890 BTC
Subtotal (without fee) 0.00244944 BTC it we are see in P&L

But i am check via Bittrex calculator, 0.00244944 BTC need add commission (fee) 0.00000612 BTC
and full total will be 0.00245557 BTC

![2017-12-06_183505](https://user-images.githubusercontent.com/18716398/33670668-a6848d04-dab6-11e7-9092-b0be05d3a70e.jpg)
![2017-12-06_183606](https://user-images.githubusercontent.com/18716398/33670683-ab3b83e8-dab6-11e7-9177-0c27f72f2675.jpg)
![2017-12-06_183724](https://user-images.githubusercontent.com/18716398/33670696-b3044dbc-dab6-11e7-81b1-cc79ebf9bd02.jpg)
![2017-12-06_185515](https://user-images.githubusercontent.com/18716398/33670878-25773422-dab7-11e7-85ab-cca429a92e84.jpg)

**Comment by cryptoeax** [comment]
OK, I think I understand what you mean now, thanks for the explanation.

You are right about this.

**Comment by cryptoeax** [comment]
Actually the problem is a bit worse, we don't even take Poloniex's fees into account when simulating a trade.  :-(

**Comment by cryptoeax** [comment]
1220402 should fix this, but it only takes effect for new trades unfortunately.  I filed #10 for the problem described in https://github.com/cryptoeax/arbbot/issues/6#issuecomment-349748595.
