### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by remipaeta** [cryptoeax/arbbot#9]
Hello everybody,

@cryptoeax can you help me ?
1) The parameter max-tx-fee-allowed is a value in BTC ?
2) The profit is always negative for me:
12:19:35: TRADING EMC2-BTC FROM POLONIEX TO BITTREX

= FUNDS ============================================
     SOURCE :     XXXXXXXX BTC
     TARGET :     0.00000000 EMC2

= SIMULATION =======================================
 TARGET MAX :     0.00000000
 SOURCE MAX :    18.65791246
   BUY RATE :     0.00013400
 BUY AMOUNT :     0.00000000
  BUY PRICE :     0.00000000
  SELL RATE :     0.00014499
SELL AMOUNT :    -0.01000000
 SELL PRICE :    -0.00000145
     PROFIT :    -0.00000145

NOT ENTERING TRADE: REQUIRING MORE EMC2

Is it normal ? I have always REQUIRING MORE $tradeable.

3) When the bot wrote Bittrex vs Poloniex, does he look for opportunities also in the direction of Poloniex vs. Bittrex?

Thank you very much for your help.

**Comment by remipaeta** [comment]
4) There is no expert section in config.ini.example.
I added it in my config.ini but the parameter allow-insecure-ui = true is not taken into account.
It's secure because I have IP filtering.

**Comment by remipaeta** [comment]
5) What are the parameters required_opportunities and balance_factor ?

**Comment by cryptoeax** [comment]
1. Yes, max-tx-fee-allowed is in BTC, 7d1690c clarifies this.

2. That typically means you don't have enough assets to enter a profitable trade.  You need to purchase more assets!  Try enabling the admin UI (set `general.admin-ui` to true after ensuring you have set up password authentication and HTTPS) and set some autobuy funds so that the bot can buy more altcoin assets.  If you don't have enough assets the bot may never be able to enter any profitable trades (you basically need to have a minimum of assets per trade to be able to cover exchange/transfer fees.)

3. Yes the bot looks for opportunities in all directions.

4. Weird, I swear I fixed this at some point, I think it got lost when moving between repos, sorry about that!  Fixed again in 7fa1582

5. I don't see any sign of either of those two parameters in the code.  :-)
